export const MOCK_TASKS = [
  {
    taskId: 'task-001',
    contactId: 'contact-001',
    contactName: 'Sarah Chen',
    company: 'Acme Corp',
    channelType: 'CALL',
    sequenceName: 'Enterprise Onboarding Flow',
    sequenceStep: 'Step 1',
    scheduledTime: '2:30 PM PST',
    dueDateTime: '2026-06-10T14:00:00-07:00',
    interactionCount: 6,
    priority: 'HIGH',
    status: 'PENDING',
    isOverdue: false,
    isAtRisk: true,
  },
  {
    taskId: 'task-002',
    contactId: 'contact-001',
    contactName: 'Sarah Chen',
    company: 'Acme Corp',
    channelType: 'EMAIL',
    sequenceName: 'Enterprise Onboarding Flow',
    sequenceStep: 'Step 2',
    scheduledTime: '2:30 PM PST',
    dueDateTime: '2026-06-10T13:00:00-07:00',
    interactionCount: 6,
    priority: 'HIGH',
    status: 'PENDING',
    isOverdue: false,
    isAtRisk: false,
  },
  {
    taskId: 'task-003',
    contactId: 'contact-002',
    contactName: 'Michael Rodriguez',
    company: 'TechFlow Inc',
    channelType: 'CALL',
    sequenceName: 'Mid-Market Follow-up',
    sequenceStep: 'Step 1',
    scheduledTime: '1:20 PM PST',
    dueDateTime: '2026-06-09T16:30:00-07:00',
    interactionCount: 7,
    priority: 'HIGH',
    status: 'OVERDUE',
    isOverdue: true,
    isAtRisk: true,
  },
  {
    taskId: 'task-004',
    contactId: 'contact-005',
    contactName: 'Karen Taylor',
    company: 'Enterprise Solutions Ltd',
    channelType: 'EMAIL',
    sequenceName: 'Enterprise Onboarding Flow',
    sequenceStep: 'Step 5',
    scheduledTime: '10:00 AM PST',
    dueDateTime: '2026-06-10T13:00:00-07:00',
    interactionCount: 16,
    priority: 'NORMAL',
    status: 'PENDING',
    isOverdue: false,
    isAtRisk: false,
  },
  {
    taskId: 'task-005',
    contactId: 'contact-006',
    contactName: 'Tom Anderson',
    company: 'SalesTech Pro',
    channelType: 'LINKEDIN',
    sequenceName: '',
    sequenceStep: '',
    scheduledTime: '2:00 PM PST',
    dueDateTime: '2026-06-10T17:00:00-07:00',
    interactionCount: 1,
    priority: 'NORMAL',
    status: 'PENDING',
    isOverdue: false,
    isAtRisk: false,
  },
];

export const MOCK_TASK_SUMMARY = {
  totalTasksToday: 5,
  completedCount: 0,
  inProgressCount: 2,
  upcomingCount: 5,
  atRiskCount: 1,
  dueTodayCount: 4,
  highPriorityCount: 3,
  progressPercent: 0,
  snoozedCount: 0,
};

export const MOCK_RECENT_ACTIVITY = [
  {
    activityId: 'act-001',
    contactId: 'contact-001',
    contactName: 'Sarah Chen',
    company: 'Acme Corp',
    channelType: 'CALL',
    summary: 'Discussed pricing concerns and ROI timeline',
    occurredAt: '2026-06-10T08:00:00-07:00',
    timeAgoLabel: '2h ago',
  },
  {
    activityId: 'act-002',
    contactId: 'contact-002',
    contactName: 'Michael Rodriguez',
    company: 'TechFlow Inc',
    channelType: 'EMAIL',
    summary: 'Requested technical documentation for security review',
    occurredAt: '2026-06-10T05:00:00-07:00',
    timeAgoLabel: '5h ago',
  },
  {
    activityId: 'act-003',
    contactId: 'contact-003',
    contactName: 'Jennifer Kim',
    company: 'DataStream Solutions',
    channelType: 'LINKEDIN',
    summary: 'Shared competitor analysis article',
    occurredAt: '2026-06-09T10:00:00-07:00',
    timeAgoLabel: '1d ago',
  },
  {
    activityId: 'act-004',
    contactId: 'contact-004',
    contactName: 'David Park',
    company: 'CloudBridge',
    channelType: 'CALL',
    summary: 'Weekly pilot program check-in',
    occurredAt: '2026-06-08T10:00:00-07:00',
    timeAgoLabel: '2d ago',
  },
];

export const MOCK_TASK_DETAILS: Record<string, any> = {
  'task-001': {
    taskId: 'task-001',
    taskTitle: 'Follow up on Q2 contract renewal',
    contactId: 'contact-001',
    contactName: 'Sarah Chen',
    company: 'Acme Corp',
    arrValue: '$240K ARR',
    scheduledDateTime: '2026-06-10T14:00:00-07:00',
    aiInsight: 'Sarah opened your last email 4 times yesterday and visited the pricing page twice. Strong buying signal — confirm budget authority before this call.',
    recommendedNextSteps: [
      'Address budget concerns with the ROI calculator',
      'Share the Acme-specific case study from the resource hub',
      'Schedule a technical deep-dive with their IT lead',
    ],
    recentActivity: [
      { date: 'May 26', channelType: 'EMAIL', summary: 'Sent proposal follow-up — opened 4x' },
      { date: 'May 24', channelType: 'CALL', summary: 'Discovery call — discussed timeline and budget' },
      { date: 'May 20', channelType: 'EMAIL', summary: 'Intro email sent — replied with questions' },
    ],
    existingNotes: 'Sarah confirmed they have budget approved but needs sign-off from CFO by end of Q2.',
  },
  'task-002': {
    taskId: 'task-002',
    taskTitle: 'Send product demo recording',
    contactId: 'contact-001',
    contactName: 'Sarah Chen',
    company: 'Acme Corp',
    arrValue: '$240K ARR',
    scheduledDateTime: '2026-06-10T13:00:00-07:00',
    aiInsight: 'Step 2 of the Enterprise Onboarding Flow. Sarah responded positively to step 1. Personalize this with the use cases she mentioned on the May 24 call.',
    recommendedNextSteps: [
      'Include the 5-minute product demo clip focused on their use case',
      'Reference the ROI numbers she mentioned in the discovery call',
      'Add a clear CTA for a follow-up call next week',
    ],
    recentActivity: [
      { date: 'May 26', channelType: 'CALL', summary: 'Introductory call completed — positive response' },
      { date: 'May 24', channelType: 'EMAIL', summary: 'Step 1 email sent and opened' },
    ],
  },
  'task-003': {
    taskId: 'task-003',
    taskTitle: 'Security requirements review call',
    contactId: 'contact-002',
    contactName: 'Michael Rodriguez',
    company: 'TechFlow Inc',
    arrValue: '$180K ARR',
    scheduledDateTime: '2026-06-09T16:30:00-07:00',
    aiInsight: 'This task is overdue. Michael last engaged 5h ago requesting security documentation. He is actively evaluating — reach out immediately to avoid losing momentum.',
    recommendedNextSteps: [
      'Call Michael directly — avoid email at this stage',
      'Lead with the security compliance deck (SOC 2, ISO 27001)',
      'Offer to loop in the solutions engineer for a technical deep-dive',
    ],
    recentActivity: [
      { date: 'May 28', channelType: 'EMAIL', summary: 'Requested technical documentation for security review' },
      { date: 'May 25', channelType: 'CALL', summary: 'Initial discovery — strong interest in enterprise tier' },
      { date: 'May 22', channelType: 'LINKEDIN', summary: 'Connected and opened initial conversation' },
    ],
  },
  'task-004': {
    taskId: 'task-004',
    taskTitle: 'Send onboarding resources — Step 5',
    contactId: 'contact-005',
    contactName: 'Karen Taylor',
    company: 'Enterprise Solutions Ltd',
    arrValue: '$310K ARR',
    scheduledDateTime: '2026-06-10T13:00:00-07:00',
    aiInsight: 'Karen has completed 4 of 5 onboarding steps with a 92 engagement score. This final step should confirm implementation timeline and introduce the CSM team.',
    recommendedNextSteps: [
      'Send the implementation checklist and CSM intro email',
      'Confirm go-live date and technical POC on their side',
      'Schedule the kickoff call with the CSM team',
    ],
    recentActivity: [
      { date: 'May 27', channelType: 'EMAIL', summary: 'Step 4 completed — Karen replied with follow-up questions' },
      { date: 'May 25', channelType: 'CALL', summary: 'Onboarding check-in call — 22 min' },
      { date: 'May 23', channelType: 'EMAIL', summary: 'Step 3 sent and completed' },
    ],
  },
  'task-005': {
    taskId: 'task-005',
    taskTitle: 'Review contract terms with legal',
    contactId: 'contact-006',
    contactName: 'Tom Anderson',
    company: 'SalesTech Pro',
    arrValue: '$85K ARR',
    scheduledDateTime: '2026-06-10T17:00:00-07:00',
    aiInsight: 'Tom is evaluating pricing at early stage. Low interaction count — prioritize relationship building before pushing contract terms.',
    recommendedNextSteps: [
      'Share redlined contract with legal team',
      'Follow up with Tom after legal review is complete',
      'Prepare competitive comparison if pricing is challenged',
    ],
    recentActivity: [
      { date: 'May 27', channelType: 'CALL', summary: 'Initial discovery call — interested in SMB plan' },
    ],
  },
};

export const MOCK_CONTACT_DETAILS: Record<string, any> = {
  'contact-001': {
    contactId: 'contact-001',
    contactName: 'Sarah Chen',
    jobTitle: 'VP of Sales Operations',
    company: 'Acme Corp',
    phone: '+1 (415) 555-0182',
    email: 'sarah.chen@acmecorp.com',
    linkedInUrl: 'https://linkedin.com/in/sarah-chen-acme',
    engagementTimeline: [
      { date: 'May 26', channelType: 'EMAIL', summary: 'Proposal follow-up sent — opened 4 times' },
      { date: 'May 24', channelType: 'CALL', summary: 'Discovery call — discussed timeline and budget' },
      { date: 'May 22', channelType: 'EMAIL', summary: 'Product overview email — link clicked 3x' },
      { date: 'May 20', channelType: 'LINKEDIN', summary: 'Connected and exchanged intro message' },
    ],
    accountInfo: {
      accountName: 'Acme Corp',
      arrValue: '$240K ARR',
      industry: 'Technology',
      website: 'acmecorp.com',
      size: '500–1,000',
    },
    dealInfo: {
      dealName: 'Acme Corp — Q2 Enterprise',
      dealStage: 'Negotiation',
      dealValue: '$240,000',
      closeDate: 'Jun 30, 2026',
    },
  },
  'contact-002': {
    contactId: 'contact-002',
    contactName: 'Michael Rodriguez',
    jobTitle: 'VP of Engineering',
    company: 'TechFlow Inc',
    phone: '+1 (628) 555-0247',
    email: 'michael.rodriguez@techflow.io',
    linkedInUrl: 'https://linkedin.com/in/michael-rodriguez-techflow',
    engagementTimeline: [
      { date: 'May 28', channelType: 'EMAIL', summary: 'Requested technical documentation for security review' },
      { date: 'May 25', channelType: 'CALL', summary: 'Initial discovery — strong interest in enterprise tier' },
      { date: 'May 22', channelType: 'LINKEDIN', summary: 'Connected and opened initial conversation' },
    ],
    accountInfo: {
      accountName: 'TechFlow Inc',
      arrValue: '$180K ARR',
      industry: 'FinTech',
      website: 'techflow.io',
      size: '200–500',
    },
    dealInfo: {
      dealName: 'TechFlow — Security Suite',
      dealStage: 'Evaluation',
      dealValue: '$180,000',
      closeDate: 'Jul 15, 2026',
    },
  },
  'contact-005': {
    contactId: 'contact-005',
    contactName: 'Karen Taylor',
    jobTitle: 'Head of Sales Enablement',
    company: 'Enterprise Solutions Ltd',
    phone: '+1 (212) 555-0729',
    email: 'karen.taylor@enterprisesolutions.com',
    linkedInUrl: 'https://linkedin.com/in/karen-taylor-esl',
    engagementTimeline: [
      { date: 'May 27', channelType: 'EMAIL', summary: 'Step 4 onboarding email — replied with follow-up questions' },
      { date: 'May 25', channelType: 'CALL', summary: 'Onboarding check-in — 22 minutes' },
      { date: 'May 23', channelType: 'EMAIL', summary: 'Step 3 onboarding email completed' },
      { date: 'May 21', channelType: 'CALL', summary: 'Step 2 walkthrough call — very engaged' },
    ],
    accountInfo: {
      accountName: 'Enterprise Solutions Ltd',
      arrValue: '$310K ARR',
      industry: 'Professional Services',
      website: 'enterprisesolutions.com',
      size: '500–1,000',
    },
    dealInfo: {
      dealName: 'ESL — Revenue Intelligence Platform',
      dealStage: 'Onboarding',
      dealValue: '$310,000',
      closeDate: 'Jun 1, 2026',
    },
  },
  'contact-006': {
    contactId: 'contact-006',
    contactName: 'Tom Anderson',
    jobTitle: 'VP of Sales',
    company: 'SalesTech Pro',
    phone: '+1 (312) 555-0833',
    email: 'tom.anderson@salestechpro.com',
    linkedInUrl: 'https://linkedin.com/in/tom-anderson-salestechpro',
    engagementTimeline: [
      { date: 'May 27', channelType: 'CALL', summary: 'Initial discovery call — interested in SMB plan' },
    ],
    accountInfo: {
      accountName: 'SalesTech Pro',
      arrValue: '$85K ARR',
      industry: 'SaaS',
      website: 'salestechpro.com',
      size: '50–100',
    },
    dealInfo: {
      dealName: 'SalesTech Pro — SMB Plan',
      dealStage: 'Discovery',
      dealValue: '$85,000',
      closeDate: 'Sep 30, 2026',
    },
  },
};

export const MOCK_EMAIL_DRAFTS: Record<string, any> = {
  'task-002': {
    taskId: 'task-002',
    contactName: 'Sarah Chen',
    contactEmail: 'sarah.chen@acmecorp.com',
    fromEmail: 'alex.chen@company.com',
    fromLabel: 'alex.chen@company.com (Gmail)',
    subject: 'Your personalized product demo — Acme Corp use case',
    bodyHtml: `<p>Hi Sarah,</p>\n<p>Following up on our conversation last week — I've put together a short demo walkthrough specifically tailored to the workflow challenges you mentioned.</p>\n<p><strong>Key highlights for Acme Corp:</strong></p>\n<ul>\n  <li>Automated renewal tracking across your 200+ accounts</li>\n  <li>Real-time risk signals for at-risk deals</li>\n  <li>Integration with your existing Salesforce setup (no migration needed)</li>\n</ul>\n<p>I've also included the ROI projections we ran based on your current process — the numbers are compelling.</p>\n<p>Would you be open to a 20-minute call this week to walk through the demo together?</p>\n<p>Best,<br/>Alex</p>`,
    sequenceName: 'Enterprise Onboarding Flow',
    sequenceStep: 'Step 2',
    dueDateTime: '2026-06-10T13:00:00-07:00',
    taskIndex: 1,
    totalTasks: 5,
  },
  'task-004': {
    taskId: 'task-004',
    contactName: 'Karen Taylor',
    contactEmail: 'karen.taylor@enterprisesolutions.com',
    fromEmail: 'alex.chen@company.com',
    fromLabel: 'alex.chen@company.com (Gmail)',
    subject: 'Final onboarding step — meet your CSM team',
    bodyHtml: `<p>Hi Karen,</p>\n<p>You've made it to the final step of the onboarding journey — congratulations!</p>\n<p>I'd love to introduce you to your dedicated Customer Success Manager, who will be your go-to contact for implementation and beyond.</p>\n<p><strong>What's next:</strong></p>\n<ol>\n  <li>Confirm your go-live date (slots available June 3–7)</li>\n  <li>Join the kickoff call with the CSM team (30 min)</li>\n  <li>Complete the implementation checklist (attached)</li>\n</ol>\n<p>You've been an absolute pleasure to work with — looking forward to seeing your results once you're live.</p>\n<p>Best,<br/>Alex</p>`,
    sequenceName: 'Enterprise Onboarding Flow',
    sequenceStep: 'Step 5',
    dueDateTime: '2026-06-10T13:00:00-07:00',
    taskIndex: 2,
    totalTasks: 5,
  },
};

export const MOCK_LINKEDIN_DRAFTS: Record<string, any> = {
  'task-005': {
    taskId: 'task-005',
    contactId: 'contact-006',
    contactName: 'Tom Anderson',
    contactTitle: 'VP of Sales',
    contactCompany: 'SalesTech Pro',
    linkedInProfileUrl: 'https://linkedin.com/in/tom-anderson-salestechpro',
    mutualConnections: 5,
    messageScript: `Hi Tom,\n\nI came across your profile and noticed you're leading sales at SalesTech Pro — great work scaling that team.\n\nWe help SaaS sales orgs like yours get real-time visibility into deal risk and pipeline health, without adding more admin work for reps.\n\nWould you be open to a quick 15-minute call this week to see if there's a fit?\n\nBest,\nAlex`,
    sequenceName: '',
    sequenceStep: '',
    dueDateTime: '2026-06-10T17:00:00-07:00',
    taskIndex: 5,
    totalTasks: 5,
  },
  'task-003': {
    taskId: 'task-003',
    contactId: 'contact-002',
    contactName: 'Michael Rodriguez',
    contactTitle: 'VP of Engineering',
    contactCompany: 'TechFlow Inc',
    linkedInProfileUrl: 'https://linkedin.com/in/michael-rodriguez-techflow',
    mutualConnections: 12,
    messageScript: `Hi Michael,\n\nI noticed you've been looking into our security compliance documentation — happy to help expedite that.\n\nWe recently completed SOC 2 Type II certification and our team has done similar security reviews with fintech companies like yours. I can have our solutions engineer share a tailored security overview if that would help speed up your evaluation.\n\nWould 20 minutes this week work to connect?\n\nBest,\nAlex`,
    sequenceName: 'Mid-Market Follow-up',
    sequenceStep: 'Step 2',
    dueDateTime: '2026-06-09T16:30:00-07:00',
    taskIndex: 3,
    totalTasks: 5,
  },
};

export const MOCK_FILTER_OPTIONS = {
  flowNames: [
    { flowId: 'flow-001', flowName: 'Enterprise Outbound Q2 2026' },
    { flowId: 'flow-002', flowName: 'Mid-Market Follow-up' },
    { flowId: 'flow-003', flowName: 'Social Selling Campaign' },
  ],
  crmFields: {
    account: [
      { fieldId: 'a-001', fieldLabel: 'Industry', fieldType: 'DROPDOWN', options: ['Technology', 'FinTech', 'SaaS'] },
    ],
    contact: [
      { fieldId: 'c-001', fieldLabel: 'Job Title', fieldType: 'TEXT' },
    ],
  },
};

export const MOCK_EMAIL_TEMPLATES = [
  {
    templateId: 'tpl-001',
    templateName: 'Discovery Follow-up',
    subject: 'Great speaking with you, {{firstName}}',
    bodyHtml: `<p>Hi {{firstName}},</p><p>It was great speaking with you today. As promised, here are the next steps we discussed...</p>`,
    category: 'Follow-up',
  },
];
