# Sync provider keys from monorepo root .env -> backend + unified-ui
# Usage: cd r-revenue-intelligence-monorepo; .\scripts\sync-env.ps1

$Root = $PSScriptRoot | Split-Path -Parent
$RootEnv = Join-Path $Root ".env"
$BackendEnv = Join-Path $Root ".env"
$UiEnv = Join-Path $Root "apps\web\.env.local"

if (-not (Test-Path $RootEnv)) {
  Write-Host "Missing root .env - add provider keys there first." -ForegroundColor Yellow
  exit 1
}

function Read-DotEnv {
  param([string]$Path)
  $map = @{}
  Get-Content $Path | ForEach-Object {
    $line = $_.Trim()
    if (-not $line -or $line.StartsWith('#')) { return }
    $idx = $line.IndexOf('=')
    if ($idx -lt 1) { return }
    $key = $line.Substring(0, $idx).Trim()
    $val = $line.Substring($idx + 1).Trim()
    if ($val.StartsWith('"') -and $val.EndsWith('"')) {
      $val = $val.Substring(1, $val.Length - 2)
    }
    $map[$key] = $val
  }
  return $map
}

$vars = Read-DotEnv $RootEnv

# Backend is at root, so it uses root .env directly. No copy needed.

# Unified UI: server routes + client-side training/smart-call keys
$groq = $vars['GROQ_API_KEY']
$openRouter = $vars['OPENROUTER_API_KEY']
$openAi = $vars['OPENAI_API_KEY']
$gemini = $vars['GEMINI_API_KEY']
$assembly = $vars['ASSEMBLYAI_API_KEY']

$uiLines = @(
  '# Auto-generated by scripts/sync-env.ps1 from monorepo root .env',
  '# Do not commit this file.',
  '',
  'NEXT_PUBLIC_API_BASE_URL=http://localhost:3001',
  'NEXT_PUBLIC_M08_API_BASE_URL=http://localhost:3001',
  'NEXT_PUBLIC_BACKEND_ORG_ID=00000000-0000-0000-0000-000000000001',
  'NEXT_PUBLIC_BACKEND_REP_USER_ID=00000000-0000-0000-0000-000000000003',
  'NEXT_PUBLIC_BACKEND_MANAGER_USER_ID=00000000-0000-0000-0000-000000000002',
  '',
  "GROQ_API_KEY=$groq",
  "NEXT_PUBLIC_GROQ_API_KEY=$groq",
  "OPENROUTER_API_KEY=$openRouter",
  "OPENAI_API_KEY=$openAi",
  "GEMINI_API_KEY=$gemini",
  "ASSEMBLYAI_API_KEY=$assembly"
)

Set-Content -Path $UiEnv -Value ($uiLines -join [Environment]::NewLine) -Encoding UTF8
Write-Host 'Synced -> apps\web\.env.local' -ForegroundColor Green
